/**
 * Tebex Checkout API
 * The Checkout APIs are designed to allow our creators to use the Tebex Checkout flow and payment acceptance capabilities without the need to set up a Tebex-powered webstore. Using these APIs allows you to create baskets with custom products (as opposed to pre-created products on our webstore platform), and send customers directly to the checkout flow to proceed with payment options.  You must receive prior authorisation before the Checkout API is enabled on your account. Please contact customer support or your account manager to discover if you qualify to use the Checkout API before beginning integration.
 *
 * The version of the OpenAPI document: 1.1.2
 * Contact: tebex-integrations@overwolf.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CreateBasketRequest {
    /**
    * The URL a customer can return to without completing checkout
    */
    'returnUrl'?: string;
    /**
    * URL the customer can return to after completing payment
    */
    'completeUrl'?: string;
    /**
    * Any custom data to be passed through the request. This will be returned in a post-completion webhook.
    */
    'custom'?: object;
    /**
    * The first name of the customer
    */
    'firstName'?: string;
    /**
    * The last name of the customer
    */
    'lastName'?: string;
    /**
    * The email address of the customer
    */
    'email'?: string;
    /**
    * An ISO8601 formatted date. After this date the basket cannot be used to checkout.
    */
    'expiresAt'?: string;
    /**
    * Automatically redirect to the complete_url provided
    */
    'completeAutoRedirect'?: boolean;
    /**
    * An ISO 3166-1 alpha-2 character code representing the customer\'s country.
    */
    'country'?: string;
    /**
    * The creator code is used to share a percentage of the payment with another party. See more about creator codes at https://docs.tebex.io/creators/tebex-control-panel/engagement/creator-codes
    */
    'creatorCode'?: string;
    /**
    * The IP address of the customer using this basket. Provide the IP if creating a basket on your server backend.
    */
    'ip'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "returnUrl",
            "baseName": "return_url",
            "type": "string"
        },
        {
            "name": "completeUrl",
            "baseName": "complete_url",
            "type": "string"
        },
        {
            "name": "custom",
            "baseName": "custom",
            "type": "object"
        },
        {
            "name": "firstName",
            "baseName": "first_name",
            "type": "string"
        },
        {
            "name": "lastName",
            "baseName": "last_name",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "expiresAt",
            "baseName": "expires_at",
            "type": "string"
        },
        {
            "name": "completeAutoRedirect",
            "baseName": "complete_auto_redirect",
            "type": "boolean"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string"
        },
        {
            "name": "creatorCode",
            "baseName": "creator_code",
            "type": "string"
        },
        {
            "name": "ip",
            "baseName": "ip",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateBasketRequest.attributeTypeMap;
    }
}

